name: e_learn
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  smooth_page_indicator: ^1.1.0
  lottie: ^2.6.0
  sizer: ^2.0.15
  animated_text_kit: ^4.2.2
  flutter_svg: ^2.0.7
  http: ^1.1.0
  shared_preferences: ^2.2.2
  global_bottom_navigation_bar: ^0.0.8
  image_picker: ^1.0.4
  firebase_storage: ^11.5.2
  firebase_core: ^2.23.0
  progress_indicator: ^0.2.2
  pinput: ^3.0.1
  dotted_border: ^2.1.0
  dropdown_button2: ^2.3.9
  video_player: ^2.8.1



dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/profile.png
    - assets/images/profile.jpeg
    - assets/lottie/
    - assets/svg/