// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzCVrR6vuHTWW-b_2JC6gHaPJ1A_i5Rgs',
    appId: '1:106570259440:web:c4f97c638fb30f2356db35',
    messagingSenderId: '106570259440',
    projectId: 'easy-learn-8803a',
    authDomain: 'easy-learn-8803a.firebaseapp.com',
    storageBucket: 'easy-learn-8803a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNBYeZk5HNjg7WU3C-hHywWBvKdKUMPX4',
    appId: '1:106570259440:android:a38270ac018f86b156db35',
    messagingSenderId: '106570259440',
    projectId: 'easy-learn-8803a',
    storageBucket: 'easy-learn-8803a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUJYbdwZRmwGa8nmVdkvmPYZc1wM5vswQ',
    appId: '1:106570259440:ios:612bc4d45137c10556db35',
    messagingSenderId: '106570259440',
    projectId: 'easy-learn-8803a',
    storageBucket: 'easy-learn-8803a.appspot.com',
    iosBundleId: 'elearning.eLearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUJYbdwZRmwGa8nmVdkvmPYZc1wM5vswQ',
    appId: '1:106570259440:ios:5b19d690a009728056db35',
    messagingSenderId: '106570259440',
    projectId: 'easy-learn-8803a',
    storageBucket: 'easy-learn-8803a.appspot.com',
    iosBundleId: 'elearning.eLearn.RunnerTests',
  );
}
